/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnviarRouteImport } from './routes/enviar'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColecoesIndexRouteImport } from './routes/colecoes.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ColecoesIdRouteImport } from './routes/colecoes.$id'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as AdminRemovidosRouteImport } from './routes/admin.removidos'
import { Route as AdminModeracaoRouteImport } from './routes/admin.moderacao'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarRoute = EnviarRouteImport.update({
  id: '/enviar',
  path: '/enviar',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesIndexRoute = ColecoesIndexRouteImport.update({
  id: '/colecoes/',
  path: '/colecoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ColecoesIdRoute = ColecoesIdRouteImport.update({
  id: '/colecoes/$id',
  path: '/colecoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRemovidosRoute = AdminRemovidosRouteImport.update({
  id: '/removidos',
  path: '/removidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModeracaoRoute = AdminModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/enviar': typeof EnviarRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registro': typeof RegistroRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/removidos': typeof AdminRemovidosRoute
  '/c/$id': typeof CIdRoute
  '/colecoes/$id': typeof ColecoesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/colecoes/': typeof ColecoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/enviar': typeof EnviarRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registro': typeof RegistroRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/removidos': typeof AdminRemovidosRoute
  '/c/$id': typeof CIdRoute
  '/colecoes/$id': typeof ColecoesIdRoute
  '/admin': typeof AdminIndexRoute
  '/colecoes': typeof ColecoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/enviar': typeof EnviarRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registro': typeof RegistroRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/removidos': typeof AdminRemovidosRoute
  '/c/$id': typeof CIdRoute
  '/colecoes/$id': typeof ColecoesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/colecoes/': typeof ColecoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/enviar'
    | '/login'
    | '/perfil'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/registro'
    | '/admin/moderacao'
    | '/admin/removidos'
    | '/c/$id'
    | '/colecoes/$id'
    | '/admin/'
    | '/colecoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/enviar'
    | '/login'
    | '/perfil'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/registro'
    | '/admin/moderacao'
    | '/admin/removidos'
    | '/c/$id'
    | '/colecoes/$id'
    | '/admin'
    | '/colecoes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/enviar'
    | '/login'
    | '/perfil'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/registro'
    | '/admin/moderacao'
    | '/admin/removidos'
    | '/c/$id'
    | '/colecoes/$id'
    | '/admin/'
    | '/colecoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  EnviarRoute: typeof EnviarRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RegistroRoute: typeof RegistroRoute
  CIdRoute: typeof CIdRoute
  ColecoesIdRoute: typeof ColecoesIdRoute
  ColecoesIndexRoute: typeof ColecoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar': {
      id: '/enviar'
      path: '/enviar'
      fullPath: '/enviar'
      preLoaderRoute: typeof EnviarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes/': {
      id: '/colecoes/'
      path: '/colecoes'
      fullPath: '/colecoes/'
      preLoaderRoute: typeof ColecoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/colecoes/$id': {
      id: '/colecoes/$id'
      path: '/colecoes/$id'
      fullPath: '/colecoes/$id'
      preLoaderRoute: typeof ColecoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/removidos': {
      id: '/admin/removidos'
      path: '/removidos'
      fullPath: '/admin/removidos'
      preLoaderRoute: typeof AdminRemovidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderacao': {
      id: '/admin/moderacao'
      path: '/moderacao'
      fullPath: '/admin/moderacao'
      preLoaderRoute: typeof AdminModeracaoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminModeracaoRoute: typeof AdminModeracaoRoute
  AdminRemovidosRoute: typeof AdminRemovidosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminModeracaoRoute: AdminModeracaoRoute,
  AdminRemovidosRoute: AdminRemovidosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  EnviarRoute: EnviarRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RegistroRoute: RegistroRoute,
  CIdRoute: CIdRoute,
  ColecoesIdRoute: ColecoesIdRoute,
  ColecoesIndexRoute: ColecoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
